### ISSUE TITLE
[1.12.2] Aether

### ISSUE THREAD

**Issue by LlamaMan122** [CyanideX/Unity-Modded#42]
**Mod**
Aether

**Download**
https://www.curseforge.com/minecraft/mc-mods/the-aether

**Optional: Asset Details**
its an entire dimension of textures so expect a lot

**Comment by CyanideX** [comment]
Sorry, at the moment we're only supporting the latest version of Minecraft (potentially one previous version if the changes are minimal) so we won't be adding Aether support just yet. Please feel free to submit this suggestion again if a newer version becomes available. 🙂 

Our artists are incredibly short on free time at the moment which is why we're only focusing on key bug fixes and current version support. Perhaps things will change in the future.
