### ISSUE TITLE
Mekanism generators

### ISSUE THREAD

**Issue by vemifol** [CyanideX/Unity-Modded#44]
**Mod**
Mekanism generators

**Download**
https://www.curseforge.com/minecraft/mc-mods/mekanism-generators

**Optional: Asset Details**
Not sure, but a lot

**Comment by CyanideX** [comment]
![image](https://media.giphy.com/media/d631TwECR94r9zlCB3/giphy.gif)

I don't understand why Mekanism is being requested. Is it because it feels out of place among other Unity textures? Do you just like Unity so much that it's instinct to request that your favorite mods receive the Unity treatment? Is there something about the current style of Mekanism that you don't like so you'd prefer a new take on it?

Mekanism IS Unity. I created the Mekanism assets. The Mekanism assets, textures and all, are done in the style of Unity. Mekanism took the original Unity textures I made for the mod and made them default.

**Comment by CyanideX** [comment]
But seriously, though... why was Mekanism requested? I would like to know why you think it doesn't already fit with Unity or what you don't like about the mod assets. 😅
