### ISSUE TITLE
[1.8.2] Hostile mob textures just dont seem to 'fit' the rest of the pack

### ISSUE THREAD

**Issue by OmaiGrundles** [CyanideX/Unity-Modded#86]
Heyo, I have been a major fan of this resource pack since I think the 1.8 days, it's been amazing to use over the years.

One of the things I always tell people when talking about this resource pack is how it works so well for modded playthroughs because all the textures are pretty close to vanilla, and thus any modded block/etc that was designed for vanilla textures will fit in perfectly. I get so used to using this texture pack that I sometimes think it *is* vanilla.

But at some point, the textures for creepers/ghasts/skeletons/endermen changed. It feels like those textures were made for an entirely different resource pack, completely abandoning the 'amazingly enhanced vanilla' feel that I think the rest of the pack has mostly adhered to. Especially the ghast and creeper. Instead of slight tweaks to freshen them up, the creeper is an entirely different color, and the ghast looks like something from a horror film instead of the cute annoying thing it usually is.

I'm not sure if i just have misinterpreted the design philosophy for this resource pack, but it just feels so out of place compared to the rest of the amazing textures used throughout. I wanted to made a post about this ages ago, but I'm terrible at expressing things like this.

**Comment by CyanideX** [comment]
Hey!

I really appreciate feedback like this and you're not wrong; the design philosophy _did_ change. Back in 1.12, I was experimenting with a few new styles and I created a separate branch called 1.12_plus to showcase these. For most vanilla blocks, the subtle changes were enough but other blocks required a bit of work to meet my standards and I noticed that I was enjoying myself a lot more when I had a little more creative freedom in the design process. This is why I strayed a bit from my original goal; I needed to be enjoying it.

I wasn't sure if the changes should be moved to a new resource pack or if I should continue with Unity so I created a poll. The vast majority of users wanted me to continue with Unity Plus and, since I didn't have time to commit to Unity **_and_** Unity Plus, Unity just changed. It was as simple as that.

There are certainly some areas of the pack that need work (or rework) and, absolutely, I took some changes to the extreme but I do listen to those people that continue to use and support my pack. If you'd like to create an issue on the [main Unity repo](https://github.com/Unity-Resource-Pack/Unity/issues/new/choose) with some suggestions, I'm more than happy to take a look at those and make changes when I have the time.

Thanks again for your thoughts and taking the time to share them. 🙂
